site_name: DnD Doc

theme: 
  name : material
  feature :
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.code.annotate

  font:
    text: Rubik
    code: Rubik Mono
  
  palette:
    #Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    #Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: teal
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    
    #Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference

nav:
  - Home: index.md
  - Classes: 
    - Artificier: classes/artificier.md
    - Barbare: classes/barbare.md
    - Barde: classes/barde.md
    - Clerc: classes/clerc.md
    - Druide: classes/druide.md
    - Ensorceleur: classes/ensorceleur.md
    - Guerrier: classes/guerrier.md
    - Magicien: classes/magicien.md
    - Moine: classes/moine.md
    - Occultiste: classes/occultiste.md
    - Paladin: classes/paladin.md
    - Rodeur: classes/rodeur.md
    - Roublard: classes/roublard.md
    - Multiclassage: classes/multiclassage.md
  - Races: 
    - Core: 
      - Demi-elfes: races/core/demi-elfe.md
      - Demi-orc: races/core/demi-orc.md
      - Drakeide: races/core/drakeide.md
      - Elfes: races/core/elfe.md
      - Gnome: races/core/gnome.md
      - Halfelins: races/core/halfelin.md
      - Humain: races/core/humain.md
      - Nains: races/core/nain.md
      - Tieffelin: races/core/tieffelin.md
    - Monstres du Multivers:
      - Changelin: races/monstres_multivers/changelin.md
      - Duergar: races/monstres_multivers/duergar.md