site_name: DnD Doc

theme: 
  name : material
  feature :
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.code.annotate

  font:
    text: Rubik
    code: Rubik Mono
  
  palette:
    #Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    #Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: teal
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    
    #Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference

nav:
  - Home: index.md
  - Classes: 
    - Artificier: classes/artificier.md
    - Barbare: classes/barbare.md
    - Barde: classes/barde.md
    - Clerc: classes/clerc.md
    - Druide: classes/druide.md
    - Ensorceleur: classes/ensorceleur.md
    - Guerrier: classes/guerrier.md
    - Magicien: classes/magicien.md
    - Moine: classes/moine.md
    - Occultiste: classes/occultiste.md
    - Paladin: classes/paladin.md
    - Rodeur: classes/rodeur.md
    - Roublard: classes/roublard.md
    - Multiclassage: classes/multiclassage.md
    - Pistolero: classes/pistolero.md
  - Races: 
    - Core: 
      - Demi-elfes: races/core/demi-elfe.md
      - Demi-orc: races/core/demi-orc.md
      - Drakeide: races/core/drakeide.md
      - Elfes: races/core/elfe.md
      - Gnome: races/core/gnome.md
      - Halfelins: races/core/halfelin.md
      - Humain: races/core/humain.md
      - Nains: races/core/nain.md
      - Tieffelin: races/core/tieffelin.md
    - Monstres du Multivers:
      - Aarakocre: races/monstres_multivers/aarakocre.md
      - Aasimar: races/monstres_multivers/aasimar.md
      - Centaure: races/monstres_multivers/centaure.md
      - Changelin: races/monstres_multivers/changelin.md
      - Conil: races/monstres_multivers/conil.md
      - Duergar: races/monstres_multivers/duergar.md
      - Eladrin: races/monstres_multivers/eladrin.md
      - Elfe des mers: races/monstres_multivers/elfe_des_mers.md
      - Fadette: races/monstres_multivers/fadette.md
      - Féral: races/monstres_multivers/feral.md
      - Firbolg: races/monstres_multivers/firbolg.md
      - Genasi: races/monstres_multivers/genasi.md
      - Githyanki: races/monstres_multivers/githyanki.md
      - Githzeraï: races/monstres_multivers/githzerai.md
      - Gnome des profondeurs: races/monstres_multivers/gnome_des_profondeurs.md
      - Gobelin: races/monstres_multivers/gobelin.md
      - Gobelours: races/monstres_multivers/gobelours.md
      - Goliath: races/monstres_multivers/goliath.md
      - Hobgobelin: races/monstres_multivers/hobgobelin.md
      - Kenku: races/monstres_multivers/kenku.md
      - Kobold: races/monstres_multivers/kobold.md
      - Minotaure: races/monstres_multivers/minotaure.md
      - Orc: races/monstres_multivers/orc.md
      - Satyre: races/monstres_multivers/satyre.md
      - Saurial: races/monstres_multivers/saurial.md
      - Shadar-Kaï: races/monstres_multivers/shadar_kai.md
      - Tabaxi: races/monstres_multivers/tabaxi.md
      - Torte: races/monstres_multivers/torte.md
      - Triton: races/monstres_multivers/triton.md
      - Yuan-ti: races/monstres_multivers/yuan_ti.md